export default {
    "en": {
        "airdrops": "AirDrops",
        "airdrop": "AirDrop",
        "history": "History",
        "date": "Date",
        "event": "Event",
        "amount": "Amount",
        "status": "Status",
        "unredeemed": "Not Redeemed",
        "redeemed": "Redeemed",
        "redeem": "Redeem",
        "redeemed_already": "Drop is Already Redeemed!!",
        "redeem_ok": "Airdrop Redeemed Successfully",
        "no_drops": "No drops Available",
        "uc_ready": "READY",
        "uc_redeemed": "REDEEMED",
        "uc_pending": "PENDING",
        "empty_reponse": "The Server Sent An Empty Response",
        "connection_failed": "Could No Complete Your Request. Internet Connection Problems?",
        "unknown_error": "An Error Occured , Updated failed",
        "merchant": "Merchant",
        "orders": "Orders",
        "settings": "Settings",
        "api_settings": "API Setting",
        "api_settings_description": "Changing could Break connection",
        "key": "Api key (Copy To plugin)",
        "regenerate": "Regenerate",
        "waiting_for_test": "Waiting for Api Test .....",
        "starting": "Starting .....",
        "response": "Api Response",
        "perform_test": "Perform Api Test",
        "confirming": "Confirming",
        "complete": "Complete",
        "unpaid": "Unpaid",
        "cancelled": "Cancelled",
        "uc_confirming": "CONFIRMING",
        "uc_complete": "COMPLETE",
        "uc_unpaid": "UNPAID",
        "uc_cancelled": "CANCELLED",
        "payment_address": "Payment Address",
        "order_address": "Select Test Order",
        "test_checkout": "Test Checkout",
        "check_checkout": "Check Your Plugin setup Here",
        "site_secret": "Site Secret (Paste From Plugin)",
        "update_secret": "Update Api Credentials",
        "site_secret_placeholder": "Set A secret for Your Site",
        "secret_saved": "New Secret Key has Been Saved. Old Key is Invalidated",
        "new_apikey_generated": "New Api Key has Been generates. Old Key is Invalidated"
    }
}
