export default {
    "en": {
        "packages": "Investment Packages",
        "no_data": "No Data",
        "uc_invested": "INVESTED {amount} {symbol}",
        "termination_fees": "Termination Fees",
        "frequency": "Frequency",
        "invests": "Investments",
        "enable": "Enable",
        "disabled": "Disabled",
        "uc_not_invested": "NO INVESTMENT",
        "balance": "Balance",
        "uc_size": "PORTFOLIO SIZE {amount}",
        "size": "Size",
        "last_payout": "Last Payout ( {percent} %)",
        "total_payout": "Total Paid Out ( {percent} %)",
        "monthly": "Monthly",
        "daily": "Daily",
        "weekly": "Weekly",
        "fortnightly": "2 Weeks",
        "semiannually": "6 Month",
        "yearly": "Yearly",
        "you_earned": "You Earned",
        "min": "Minimum",
        "max": "Maximum",
        "last_date": "Last Interest",
        "next_date": "Last Payout Date",
        "invest_here": "Invest Package",
        "active": "Active",
        "inactive": "Not Active",
        "invest": "Invest",
        "history": "History",
        "date": "Date",
        "amount": "Amount",
        "uuid": "Unique ID",
        "compounding": "Compounding",
        "status": "Status",
        "payout": "Payout",
        "payouts": "Payouts",
        "interest": "Interest",
        "name": "Name",
        "uc_redeemed": "REDEEMED",
        "uc_closed": "CLOSED",
        "uc_unredeemed": "READY",
        "uc_reinvested": "COMPOUNDED",
        "uc_complete": "COMPLETE",
        "uc_queued": "QUEUED",
        "redeem": "Redeem",
        "percent": "Percent",
        "min_return": "Min Return",
        "max_return": "Max Return",
        "invest_return": "Returns Upto",
        "invest_in": "Invest In",
        "min_period": "Min Duration",
        "days": "Days",
        "upto": "Upto",
        "confirm": "Confirm Investment of {amount}",
        "confirm_investment": "Confirm Investment",
        "confirm_description": "By Clicking the Button Below your agree to out Term and conditions of the investment",
        "tos": "View Terms",
        "close": "Close",
        "empty_reponse": "The Server Sent An Empty Response",
        "connection_failed": "Could No Complete Your Request. Internet Connection Problems?",
        "unknown_error": "An Error Occured , Updated failed",
        "delete_success": "{item} Deleted successfully",
        "uncompound_success": "Compounding (Reinvestment of Earned Interest ) Disabled Successfuly",
        "compound_success": "Compounding (Reinvestment of Earned Interest ) Enabled Successfuly",
        "invest_success": "Investment Created Successfully",
        "redeem_success": "Interest Redeemed to Your Main Balance Successfully",
        "mass_compounding_success": "Compounding (Reinvestment of Earned Interest ) Enabled On All Your Investments Successfuly",
        "low_balance": "Low Balance! Required {required} , Available {available}",
        "minimimum_is": "Minimum Invest Amount for this Package is {min}",
        "maximum_is": "Maximum Invest Amount for this Package is {max}",
        "earned": " Earned",
        "redeemed_already": "Interest is Already Redeemed!!"
    }
}
