export default {
    "en": {
        "packages": "Loan Packages",
        "balance": "Balance",
        "size": "Size",
        "actions": "Actions",
        "last_payback": "Last Repayment ( {percent} %)",
        "total_payback": "Total Paid Back ( {percent} %)",
        "monthly": "Monthly",
        "daily": "Daily",
        "weekly": "Weekly",
        "fortnightly": "Every 2 Weeks",
        "semiannually": "Every 6 Months",
        "yearly": "Yearly",
        "you_earned": "You Earned",
        "min": "Minimum",
        "max": "Maximum",
        "last_date": "Last Repayment",
        "next_date": "Next Repayment",
        "take_loan": "Get Loan",
        "active": "Active",
        "inactive": "Not Active",
        "loan": "Loan",
        "loans": "Loans",
        "history": "History",
        "date": "Date",
        "amount": "Amount",
        "uuid": "Unique ID",
        "status": "Status",
        "payback": "Repayment",
        "paybacks": "Repayments",
        "name": "Name",
        "percent": "Percent",
        "return": "Return",
        "period": "Duration",
        "days": "Days",
        "upto": "Upto",
        "confirm": "Confirm Loan of {amount}",
        "confirm_loan": "Confirm Loan",
        "confirm_description": "By Clicking the Button Below your agree to our Term and conditions of the loan",
        "tos": "View Terms",
        "close": "Close",
        "empty_reponse": "The Server Sent An Empty Response",
        "connection_failed": "Could No Complete Your Request. Internet Connection Problems?",
        "unknown_error": "An Error Occured , Updated failed",
        "delete_success": "Loan Cancelled successfully",
        "repay_success": "Loan Installment Settled Successfully",
        "loan_success": "Loan Granted Successfully. A repayment Schedule has been drafted",
        "referral": "Referral Earnings",
        "payback_desc": " Repayment in {count} Installments of {amount} {paybacks}.",
        "total_portfolio": "Your Total Portfolio is {amount}.",
        "get_loan": "Get This Loan.",
        "collateral": "Loan Collateral.",
        "uc_closed": "CLOSED.",
        "uc_servicing": "SERVICING",
        "repaid": "Repaid ",
        "repayments": "Repayments ",
        "uclate": "LATE ",
        "late": "Late ",
        "uc_paid": "PAID ",
        "unpaid": "Unpaid ",
        "repay": "Repay ",
        "no_data": "No Data ",
        "select_image": "Select Logo ",
        "low_balance": "Low Balance! Required {required} , Available {available}"
    }
}
