export default {
    "en": {
        "ref": "Referral",
        "refs": "Referrals",
        "referral": "Referral",
        "referrals": "Referrals",
        "history": "Histroy",
        "com": "Commission",
        "coms": "Commissions",
        "tree": "Tree",
        "mlm_tree": "Multilevel Tree Structure",
        "refs_coms": "Referrals and Commisssion",
        "user": "User",
        "downline": "Downline Count",
        "date": "Date",
        "amount": "Amount",
        "actions": "Actions",
        "name": "Name",
        "percent": "Percent",
        "return": "Return",
        "tos": "View Terms",
        "close": "Close",
        "status": "Status",
        "reward": "Commission",
        "level": "Level",
        "uc_ready": "READY",
        "uc_redeemed": "REDEEMED",
        "redeem": "Redeem",
        "empty_reponse": "The Server Sent An Empty Response",
        "connection_failed": "Could No Complete Your Request. Internet Connection Problems?",
        "unknown_error": "An Error Occured , Updated failed",
        "uc_pending": "PENDING",
        "redeem_ok": "Reward redeemed Successfully Successfully"
    }
}
