export default {
    "en": {
        "withdraw": "Send {symbol} to Address / Users",
        "deposit_uppercase": "DEPOSIT",
        "address": "Address",
        "balance": "Balance",
        "total_balance": "Total Balance",
        "total_lending": "Total Lending",
        "total_investing": "Total Investing",
        "history": "History",
        "deposits": "Deposits",
        "withdrawals": "Withdrawals",
        "transfers": "Transfers",
        "topups": "Topups",
        "txid": "Transaction ID",
        "user": "User",
        "date": "Date",
        "amount": "Amount",
        "tx_id": "Txid",
        "coin_address": "{symbol} Address,  Account Number or User Email",
        "status": "Status",
        "actions": "Actions",
        "uc_unavailable": "UNAVAILABLE",
        "uc_pending": "PENDING",
        "uc_complete": "COMPLETE",
        "uc_rejected": "REJECTED",
        "uc_other_balances": "OTHER BALANCES",
        "uc_deposit": "DEPOSIT",
        "uc_queued": "QUEUED",
        "uc_failed": "FAILED",
        "uc_unconfirmed": "UNCONFIRM",
        "uc_withdraw": "WITHDRAW",
        "uc_referral": "REFERRAL",
        "uc_debit": "DEBIT",
        "uc_credit": "CREDIT",
        "uc_shift": "SHIFT",
        "uc_interest": "INTEREST",
        "no_data": "No Data Available",
        "to": "To",
        "from": "From",
        "ok": "OK",
        "off": "OFF",
        "failed": "FAIL",
        "type": "Type",
        "uc_fees": "FEES",
        "fees": "fees",
        "description": "Description",
        "scan_qr": "Scan to Deposit",
        "money_request": "Money Request",
        "no_money_request": "No Request Found<",
        "request_money": "Request Money",
        "tx_queued": "Note: Transactions are queued and May take upto to 10 minutes To Appear on the Blockchain. ",
        "withdraw_queued": "Withdraw has beed Queued and will reviewed by Out Team Shortly. This could take upto 60 Minutes",
        "select": "Select Wallet",
        "select_note": "Select The Wallet To Send From",
        "amount_in": "Amount in {symbol}",
        "enter": "Enter",
        "fees_note": "Fees are automatically calaculated and Set.",
        "send_now": "Send Now",
        "invalid_amount": "Invalid Amount.",
        "ok_amount": "Amount is OK.",
        "send_more": "Send Some More.",
        "view_tx": "View Transaction.",
        "send_success_desc": "Your Transaction has been sent successfully.",
        "send_success": "Send Successfully.",
        "send_queued": "Transaction Queued!.",
        "send_failed": "Oops! Transaction failed!.",
        "send_failed_desc": "Transaction couldn’t be processed now. If this Problem Persists, Please Contact Support",
        "send_again": "Try to Send Again",
        "account": "Account",
        "account_no": "ACCOUNT NO:",
        "move_funds_to_deposit": "Move Balance To Deposit",
        "deposit_now": "Move To Deposit Now",
        "low_balance": "Your Balance is Low. Required {required} , Available {available}",
        "mismatch": "Wallet Mismatch! You Cannot from {fsym} to  {tosym} Wallet",
        "invalid_account": "Invalid Account Number! Please Verify Account and Try Again",
        "invalid_email": "User Acount Was Not found!. Please Check email",
        "moved_success": "{amount} Moved To your Deposit Wallet Successfully",
        "deposit_request": "Request Deposit"
    }
}
